[project]
name = "yt-dlp-gui"
version = "0.1.0"
description = "A personal project to create a user-friendly UI interface for yl-dlp"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "customtkinter>=5.2.2",
    "pillow>=10.2.0",
    "yt-dlp>=2024.12.23",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.2.0",
]
